-- Tabela de Login [sincronização em nuvem]
CREATE TABLE Login (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Senha VARCHAR(255) NOT NULL,
  SenhaUnica VARCHAR(10) UNIQUE,
  Nome VARCHAR(255) NOT NULL
);

ALTER TABLE Login
  MODIFY ID INT AUTO_INCREMENT ZEROFILL;

-- Tabela de Notas [sincronização em nuvem e local]
CREATE TABLE Notas (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Titulo VARCHAR(255) NOT NULL,
  Texto TEXT NOT NULL
);

ALTER TABLE Notas
  MODIFY ID INT AUTO_INCREMENT,
  MODIFY ID INT ZEROFILL;
